# Generated by Django 5.1.3 on 2024-11-10 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElectrocarsAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='power_report',
            name='report_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 10, 9, 30, 32, 307909, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
