# Generated by Django 5.1.3 on 2024-11-10 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElectrocarsAPI', '0002_alter_power_report_report_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='power_report',
            name='average_power',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='power_report',
            name='report_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 10, 9, 56, 40, 620786, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
