# Generated by Django 5.1.3 on 2024-11-26 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElectrocarsAPI', '0003_power_report_average_power_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='power_report',
            old_name='average_power',
            new_name='sum_power',
        ),
        migrations.AlterField(
            model_name='power_report',
            name='report_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 26, 10, 41, 52, 417740, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
