# Generated by Django 5.1.4 on 2025-02-11 23:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElectrocarsAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='power_report',
            name='qr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='power_report',
            name='report_date',
            field=models.DateField(default=datetime.datetime(2025, 2, 11, 23, 58, 0, 96972, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
